### PR TITLE
T login signup pages

### LINKED ISSUE #14: Login and Signup pages
The login and sign up pages have been redesigned with the style of Lofft, this should be updated.

### Todo
- [ ] Update back button icon 
- [ ] Change input fields to purple
- [ ] Add view password eye
- [ ] Add terms and conditions section

The addition of google and apple authentication should be completed next on their branch.

### PR DESCRIPTION
**Pull request by jhibbeard89**
#### Notion Link

- [Notion Link](https://www.notion.so/lofftapp/T-Login-Signup-page-2b1bf9b6fe2649cfb7401564b4adb3f6)

### Issues Ref

- closes #14 

### Assigned Devs

- @jhibbeard89 

### Changes and Updates

- Change siginin and signup screen inline with Figma
- Created standard form that is shared between the two pages
- New components added documentation is needed for these. 

### Added APIs, Webpack or Yarn/NPM installs

- Bouncy Checkbox

### Notes

- _No new notes_

### CODE REVIEW

**Comment by jhibbeard89** [comment]
## Close day 30.11.21

The update is not yet complete, some issues need to be resolved tomorrow with the buttons only accepting navigation routing, though in some cases the buttons are used for other things such as logging in. This should be updated. 

To do: 
- [ ] Add Google and Apple icons to buttons
- [ ] Update back button inline with design (This could be a problem needs research)
- [ ] Closing eye needs to be added to password field. 
- [ ] Update core button functions

**Review by jhibbeard89 — COMMENTED** [review]
Latest update reviewed

**Review by AdamTomczyk — APPROVED** [review]
✔

**Comment by jhibbeard89** [comment]
@AdamTomczyk yo if you're happy want to have a look everything has been done now and is up to date.

**Pull request merged**
