### PR TITLE
Fixed some layout in android, thought most due to bug in android emul…

### LINKED ISSUE #27: Issue with swipe and margin in android
**Describe the bug**
- Within the android emulator the scroll stops sometimes at 50%, and the top margin of the home page is white, this is due to the margin, use padding instead

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'landing page'
3. Scroll down to 'swipe L/R '

**Expected behaviour**
- The screen should pass easily to the next screen. 

**Screenshots**
Screenshot_20211203_122507

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Pixel 4 emulator
 - OS: [e.g. iOS8.1] Android
 - Browser [e.g. stock browser, safari] NA

**Additional context**

### PR DESCRIPTION
**Pull request by jhibbeard89**
#### Notion Link

- [Notion Link]()

### Issues Ref

- closes #27 

### Changes and Updates

- Removed some excessive padding and comments

### Added APIs, Webpack or Yarn/NPM installs

- _No Added APIs_

### Notes

- The issue with the white space is caused by the emulator and should be missing on the device. thought this needs to be checked on an android before release of MVP.

### CODE REVIEW

**Comment by jhibbeard89** [comment]
Checked the display in Pixel 3a emulator and appears to work as expected, issue with top bar appears to only occur on the 4 emulator, again this should be confirmed on device.

**Comment by jhibbeard89** [comment]
# Close 12.12

- Updated the layout 
- Found no issue with top margin on android, after some googling it was an issue with the emulator pixel 4. 
- Some alignment issues to be resolved tomorrow. 

## to-do
- [ ] Update alignment to show easy changes from page to page. 
- [ ] Some swipe panels expand beyond the screen, hiding the image edges, to resolve this.

**Comment by jhibbeard89** [comment]
# Bug on Pixel 4

The bug appears on the pixel 4 device on checking so the info about the emulator does not apply to this. There is a couple of solutions to try and remove this.

**Review by AdamTomczyk — APPROVED** [review]
Approved 🥸

**Pull request merged**
